name: Instagram Monitor

on:
  schedule:
    - cron: '0 * * * *' # Vérification automatique toutes les heures
  workflow_dispatch: # Permet le lancement manuel avec le bouton

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Mis à jour pour Node 24

      - name: Set up Python
        uses: actions/setup-python@v5 # Mis à jour pour Node 24
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run script
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          IG_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          TIME_INTERVAL: '600'
        run: python bot.py
